### ISSUE TITLE
Rou'a - implement a workflow

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cms-dpoa-getting-started#78]
Implement a two-step workflow in argo with 

1.  use `cernopendata/cernopendata-client` container image to get a file with a list of files and their sizes of one open data record
     - https://cernopendata-client.readthedocs.io/en/latest/installation.html#docker
     - see https://cernopendata-client.readthedocs.io/en/latest/usage.html#listing-available-data-files how the files and their sizes 
    use for example record http://opendata.cern.ch/record/6010 
2. use another container e.g. `python:3` to read the file created in step 1 and divide the files into groups of roughly equal size. Give these new listings as the output of this step
    - write the python script to compute the total size and then divide the listing into groups (you can start simple and expect that the files have a roughly equal site)
    - give the size of groups as a parameter

**Comment by roua-altamimi** [comment]
for the record download gives this error 

```
 docker run -it --rm cernopendata/cernopendata-client download-files --recid 6010
==> Downloading file 1 of 1404
  -> File: ./6010/00992A80-DF70-E211-9872-0026189437FE.root
Traceback (most recent call last): (33%)
  File "/usr/local/bin/cernopendata-client", line 11, in <module>
    load_entry_point('cernopendata-client==0.2.0', 'console_scripts', 'cernopendata-client')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cernopendata_client/cli.py", line 344, in download_files
    download_single_file(path=path, file_location=file_location, protocol=protocol)
  File "/usr/local/lib/python3.6/site-packages/cernopendata_client/downloader.py", line 109, in download_single_file
    c.perform()
pycurl.error: (18, 'transfer closed with 2184044197 bytes remaining to read') 
```
